plugins: [jekyll-paginate]

permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: "page/:num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,gitment.css,post.css]
      scripts : [gitment.js, post.js]



title: "xiaxuele"
email: xiaxuele10086@163.com
description: ""
github:
  username: xiaxuele
#swiftype:
#  searchId: iXZyPokVfxFaBTvi64Y6
gitment:
    repo: blog
    client_id: 6f82cf01ce005a659c48
    client_secret: 72cc0f28e46da794cf78278e8d84593d7618511f

url: "https://xiaxuele.github.io"
imgrepo: "https://bit-ranger.github.io/blog/static/img"


#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

